{
 "title": "Experimental Site 1 - Live Data",
 "description": "Data acquired by 3G service from the main computer. The data comes from from 8 differents subsystems, thus 32 light sensors monitoring 2 bandwidths.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "GlobalView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Data TimeStamp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(timeStamp, \"%Y-%m-%d %H:%i:%S\") AS \"timeStamp\"\r\nFROM DetectorUnitsData\r\nORDER BY timeStamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Last Low Resolution Capture",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 1 },
   "options": {
    "content": "<img src=\"/public/img/lowres.jpg\" alt=\"test\" height=100% width=100%>\n\n"
   }
  },
  {
   "title": "325mm Optical Irradiance in Shrubs",
   "type": "graph",
   "description": "Blue Power in Shrubs for all heights",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  powerMean AS \"Blue irradiance\",\n  wavelength as metric\nFROM PhotodiodeData\nWHERE\n  $__timeFilter(timeStamp) AND\n  location = 'S' AND\n  wavelength = '400' AND\n  height = \"325.00\"\nORDER BY timeStamp, height DESC;"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  powerMean AS \"IR irradiance\",\n  wavelength as metric\nFROM PhotodiodeData\nWHERE\n  $__timeFilter(timeStamp) AND\n  location = 'S' AND\n  wavelength = '700' AND\n  height = \"325.00\"\nORDER BY timeStamp, height DESC;"
    }
   ]
  },
  {
   "title": "325mm Optical Irradiance in Field",
   "type": "graph",
   "description": "Blue Power in Shrubs for all heights",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  powerMean AS \"Blue irradiance\",\n  wavelength as metric\nFROM PhotodiodeData\nWHERE\n  $__timeFilter(timeStamp) AND\n  location = 'F' AND\n  wavelength = '400' AND\n  height = \"325.00\"\nORDER BY timeStamp, height DESC;"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  powerMean AS \"IR irradiance\",\n  wavelength as metric\nFROM PhotodiodeData\nWHERE\n  $__timeFilter(timeStamp) AND\n  location = 'F' AND\n  wavelength = '700' AND\n  height = \"325.00\"\nORDER BY timeStamp, height DESC;"
    }
   ]
  },
  {
   "title": "Last Detectors Mean Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT humidityMean FROM DetectorUnitsData ORDER BY timeStamp DESC LIMIT 8;"
    }
   ]
  },
  {
   "title": "Last Detectors Mean Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperatureMean FROM DetectorUnitsData ORDER BY timeStamp DESC LIMIT 8;"
    }
   ]
  },
  { "title": "Power Data #1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Blue Power in Field",
   "type": "graph",
   "description": "Blue Power inField for all heights",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  height AS metric,\n  powerMean\nFROM PhotodiodeData\nWHERE\n  $__timeFilter(timeStamp) AND\n  location = 'F' AND\n  wavelength = '400'\nORDER BY timeStamp, height DESC;"
    }
   ]
  },
  {
   "title": "IR Power in Field",
   "type": "graph",
   "description": "IR Power inField for all heights",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  height AS metric,\n  powerMean\nFROM PhotodiodeData\nWHERE\n  $__timeFilter(timeStamp) AND\n  location = 'F' AND\n  wavelength = '700'\nORDER BY timeStamp, height DESC;"
    }
   ]
  },
  {
   "title": "Blue Power in Shrubs",
   "type": "graph",
   "description": "Blue Power in Shrubs for all heights",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  height AS metric,\n  powerMean\nFROM PhotodiodeData\nWHERE\n  $__timeFilter(timeStamp) AND\n  location = 'S' AND\n  wavelength = '400'\nORDER BY timeStamp, height DESC;"
    }
   ]
  },
  {
   "title": "IR Power in Shrubs",
   "type": "graph",
   "description": "IR Power in Shrubs for all heights",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  height AS metric,\n  powerMean\nFROM PhotodiodeData\nWHERE\n  $__timeFilter(timeStamp) AND\n  location = 'S' AND\n  wavelength = '700'\nORDER BY timeStamp, height DESC;"
    }
   ]
  },
  {
   "title": "Power Data #2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Field Irradiance Radar Plot",
     "type": "snuids-radar-panel",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(timeStamp),\n  height AS metric,\n  powerMean\nFROM PhotodiodeData\nWHERE\n   wavelength='400' AND\n  location = 'F'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  $__time(timeStamp),\n  powerMean,\n  height as metric\nFROM PhotodiodeData\nWHERE\n  wavelength='700' AND\n  location = 'F'\nORDER BY timeStamp;"
      }
     ]
    },
    {
     "title": "Shrubs Irradiance Radar Plot",
     "type": "snuids-radar-panel",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(timeStamp),\n  height AS metric,\n  powerMean\nFROM PhotodiodeData\nWHERE\n   wavelength='400' AND\n  location = 'S'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  $__time(timeStamp),\n  powerMean,\n  height as metric\nFROM PhotodiodeData\nWHERE\n  wavelength='700' AND\n  location = 'S'\nORDER BY timeStamp;"
      }
     ]
    }
   ]
  },
  {
   "title": "RAW DATA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cierge 1",
     "type": "graph",
     "description": "Cierge 1",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd1DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '1'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd4DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '1'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd2DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '1'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd3DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '1'\nORDER BY timeStamp"
      }
     ]
    },
    {
     "title": "Cierge 2",
     "type": "graph",
     "description": "Cierge 2",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd1DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '2'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd4DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '2'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd2DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '2'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd3DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '2'\nORDER BY timeStamp"
      }
     ]
    },
    {
     "title": "Cierge 3",
     "type": "graph",
     "description": "Cierge 3",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd1DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '3'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd4DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '3'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd2DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '3'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd3DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '3'\nORDER BY timeStamp"
      }
     ]
    },
    {
     "title": "Cierge 4",
     "type": "graph",
     "description": "Cierge 4",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd1DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '4'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd4DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '4'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd2DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '4'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd3DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '4'\nORDER BY timeStamp"
      }
     ]
    },
    {
     "title": "Cierge 5",
     "type": "graph",
     "description": "Cierge 5",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd1DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '5'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd4DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '5'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd2DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '5'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd3DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '5'\nORDER BY timeStamp"
      }
     ]
    },
    {
     "title": "Cierge 6",
     "type": "graph",
     "description": "Cierge 6",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd1DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '6'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd4DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '6'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd2DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '6'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd3DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '6'\nORDER BY timeStamp"
      }
     ]
    },
    {
     "title": "Cierge 7",
     "type": "graph",
     "description": "Cierge 7",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd1DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '7'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd4DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '7'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd2DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '7'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd3DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '7'\nORDER BY timeStamp"
      }
     ]
    },
    {
     "title": "Cierge 8",
     "type": "graph",
     "description": "Cierge 8",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd1DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '8'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd4DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '8'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd2DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '8'\nORDER BY timeStamp"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(timeStamp) AS \"time\",\n  pd3DigitalNumberMean\nFROM DetectorUnitsData\nWHERE\n  $__timeFilter(timeStamp) AND\n  unitID = '8'\nORDER BY timeStamp"
      }
     ]
    }
   ]
  },
  { "title": "Images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Last Low Resolution Capture",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "options": {
    "content": "<img src=\"/public/img/lowres.jpg\" alt=\"test\" height=100% width=100%>\n\n"
   }
  },
  {
   "title": "Last High Resolution Capture",
   "type": "text",
   "gridPos": { "h": 23, "w": 16, "x": 6, "y": 33 },
   "options": {
    "content": "<img src=\"/public/img/highres.jpg\" alt=\"test\" height=100% width=100%>\n\n"
   }
  }
 ]
}